### ISSUE TITLE
Fix section on Leo algorithms

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/Marpa-arxiv-paper#11]
@dabrahams has pointed out more problems with section 6, on the Leo algorithm.

**Comment by jeffreykegler** [comment]
@dabrahams As of commit https://github.com/jeffreykegler/Marpa-arxiv-paper/commit/f33cbd56c47db12f8d237356aae03ecec4dc0735 the fix is in.  I have proofread sections 5 and 6 and the other places I've changed.  It'd be a good time to look at it, if you care to.

I next plan to re-read the entire paper, with the intent of preparing a v3 for upload to ariv.org.

**Comment by jeffreykegler** [comment]
I will wait a few days (perhaps as much as a week) and, absent feedback to the contrary, will close this issue.

**Comment by dabrahams** [comment]
@jeffreykegler I finally got around to looking at the differences; I don't see anything in what you did that addresses the [original issue](https://github.com/jeffreykegler/Marpa--R2/issues/288), which was about better explaining how one reconstructs parse trees when some completions are missing from the chart due to the Leo optimization.  In fact, I think that information isn't treated in this paper at all.  IIRC the closest thing to an explanation of that exists in the CWeb sources of libmarpa, as you pointed to [here](https://colabti.org/irclogger/irclogger_log/marpa?date=2022-12-03#l44).

**Comment by jeffreykegler** [comment]
I think you're right, evaluation in the face of Leo optimization is not fully documented anywhere outside the source.  The paper just touches on the time bounds.  The paper was only intended to cover the recognizer, though it does touch on other things.  Once I've made the new release of Marpa::R2 and caught up on problems with the original paper, I'll look back on this issue.

At that point I may create a new issue, and perhaps address the evaluation issues in a new paper.

**Comment by jeffreykegler** [comment]
@dabrahams  In c3a4deb I've written up pseudo-code for the restoration of Leo-hidden completions.  I've proof-read it, and hope it's right.  It is [here](https://github.com/jeffreykegler/Marpa-arxiv-paper/blob/main/pseudo4da.html).

**Comment by dabrahams** [comment]
I've had a quick look and am finding it a little hard to grasp still; I'll have to spend more time with it.

**Comment by jeffreykegler** [comment]
For a dozen lines of pseudo-code, it's amazingly tricky.  My proof-reading of it took me through several drafts.

**Comment by dabrahams** [comment]
A couple of questions while I work through the  example [here](https://github.com/jeffreykegler/Marpa--R2/issues/288#issuecomment-1339763254):

I am assuming Current(x) means the Earley set in which x appears?

I don't know how you're defining the causation of a LIM, and there are a number of reasonable options.  I can try to deduce your definition, but it'd be easier if you'd just tell me ;-)

**Comment by jeffreykegler** [comment]
I improved the writeup in commit eb5cdec.  I hope it addresses your questions.  My method involves links aka causations aka confluences, which libmarpa stores with each parse item.  I think this might differ from your approach, which is perhaps less storage-intensive.  My pseudo-code assumes the links are there for existing parse items, and adds them, if necessary, to the EIMs that it requires.

While I was at it, I noticed `Current()` is not really a function, turned it into the constant `current` and documented it. :-)

**Comment by dabrahams** [comment]
Unfortunately it doesn't address either of my questions, which I'll rephrase here:

1. What does Current(x) mean in the original example or current mean in the revised one?
2. What is recorded as the causation for a Leo item?

My predot origins are sufficient to reconstruct causations as I understand them, so what we're doing is equivalent.

**Comment by jeffreykegler** [comment]
Current is the location of the `top` EIM.

A causation is a duple whose elements are parse items.  In C, implementation could be via pointers.

**Comment by dabrahams** [comment]
I understand the _representation_ of causations.  What I want to know is, for a LIM, where does each element of that duple point?

The mainstem and tributary of an EIM are well-defined and easily understood.  Less so for a LIM.  I'm gonna guess… that 
- the tributary is the penult EIM whose completion is prevented by the LIM.
- the mainstem is the Leo predecessor of the tributary if any, and is nil otherwise.

**Comment by jeffreykegler** [comment]
The mainstem of the causation of a LIM is either another LIM, or undefined.  The tributary, which is always defined, is an Earley item.  In the "Leo Memoization" section of the paper, the tributary is the `bottom` EIMT, and the mainstem is the LIMT Predecessor of `bottom`, if that exists.

**Comment by jeffreykegler** [comment]
This means that your guess in https://github.com/jeffreykegler/Marpa-arxiv-paper/issues/11#issuecomment-1358162938  is correct, if I read it right.

**Comment by dabrahams** [comment]
> the tributary is the bottom EIMT

Sorry, I don't think it's possible for the bottom EIMT to contribute to the generation of an LIMT.  IIUC all the related Leo items occur in sets before that of the `bottom` EIMT and thus were generated before it. In [this example](https://github.com/jeffreykegler/Marpa--R2/issues/288#issuecomment-1339763254) `bottom`s are items 39 and 40, but the LIMs are 4,6, 12, 21, 23, and 31.  By my guess, the tributaries of those LIMs are 5,7, 13, 22, 24, and 32 respectively.

**Comment by jeffreykegler** [comment]
A `bottom` EIM must be Leo unique, and therefore a penult.  If I read your example correctly, items 39 and 40 are completions.  Your guessed-at tributaries (5,7, 13, 22, 24, and 32) are all penults, as they should be.

**Comment by dabrahams** [comment]
Oh!  I thought `bottom` meant the not-omitted completion at the bottom of the Leo optimized parse; as you mentioned somewhere else(?) only the top and bottom of the parse get completions.  That explains the confusion.

Anyway, I worked through [this example](https://github.com/jeffreykegler/Marpa--R2/issues/288#issuecomment-1339763254)  and it looks like your logic checks out:

- top = completion 40

- there are two causations, both of which happen to be Leo causations, represented by the predot
  origins 2 and 8.

1. predot origin 2: [lim0 = LIM6, baseEIM = EIM39]
   1. workingLim = LIM6
   1. previousCompletion = EIM39
   1. while: LIM6 exists
      1. [ previousLIM=nil, workingBase=EIM7 ] = causation(workingLIM)
      1. Let completion = { B ::= C•, origin 2 }
      1. Require completion in current adds it to set 9 as c0
      1. Require the causation [ EIM7, EIM39 ] for c0
      1. workingLim = nil
      1. previousCompletion = c0
   1. while: NIL does not exist; we're done
   
1. predot origin 8: [lim0 = LIM31, baseEIM = EIM42]
   1. workingLim = LIM31
   1. previousCompletion = EIM42
   1. while: LIM31 exists
      1. [ previousLIM=LIM23, workingBase=EIM32 ] = causation(LIM31)
      1. Let completion = { C ::= 'y' 'z' A•, origin 6 }
      1. Require completion in current adds it to set 9 as c1
      1. Require the causation [ EIM32, EIM42 ] for c1
      1. workingLim = LIM23
      1. previousCompletion = c1
   1. while: LIM23 exists
      1. [ previousLIM=LIM21, workingBase=EIM24 ] = causation(LIM23)
      1. Let completion = { B ::= C•, origin 6 }
      1. Require completion in current adds it to set 9 as c2
      1. Require the causation [ EIM24, c1 ] for c2
      1. workingLim = LIM21
      1. previousCompletion = c2
   1. while: LIM21 exists
      1. [ previousLIM=LIM12, workingBase=EIM22 ] = causation(LIM21)
      1. Let completion = { A ::= 'w' 'x' B•, origin 4 }
      1. Require completion in current adds it to set 9 as c3
      1. Require the causation [ EIM22, c2 ] for c3
      1. workingLim = LIM12
      1. previousCompletion = c3
   1. while: LIM12 exists
      1. [ previousLIM=LIM6, workingBase=EIM13 ] = causation(LIM12)
      1. Let completion = { C ::= 'y' 'z' A•, origin 2 }
      1. Require completion in current adds it to set 9 as c4
      1. Require the causation [ EIM13, c3 ] for c4
      1. workingLim = LIM6
      1. previousCompletion = c4
   1. while: LIM6 exists
      1. [ previousLIM=LIM4, workingBase=EIM7 ] = causation(LIM6)
      1. Let completion = { B ::= C•, origin 2 }
      1. Require completion in current adds it to set 9 as c5
      1. Require the causation [ EIM7, c4 ] for c5
      1. workingLim = LIM4
      1. previousCompletion = c5
   1. while: LIM4 exists
      1. [ previousLIM=nil, workingBase=EIM5 ] = causation(LIM4)
      1. Let completion = { A ::= 'w' 'x' B•, origin 0 }
      1. Require completion in current adds it to set 9 as c6
      1. Require the causation [ EIM5, c5 ] for c6
      1. workingLim = nil
      1. previousCompletion = c6
   1. while: nil does not exist; we're done

**Comment by jeffreykegler** [comment]
I probably at some point in some context did use the term `bottom` for a completion.  Things like this are why I am mining fluvial mechanics for non-overloaded terms.  When this paper is revised that EIM will be called `tributary`.

**Comment by dabrahams** [comment]
Well all tributaries of EIMs are completions, neh?

I think you should find another word or qualify it somehow; tributary describes its relationship to the last omitted completion in a chain, but not its relationship to the whole deterministic reduction path… oh, but maybe by "that EIM" you don't mean the not-omitted completion I thought you were referring to but the bottom EIMT you mentioned in [this comment](https://github.com/jeffreykegler/Marpa-arxiv-paper/issues/11#issuecomment-1358171979).  Oof. Terminology is hard!

**Comment by jeffreykegler** [comment]
Some poet once said that poems are never finished, they are abandoned.  Terminology is like that.  I change it when it proves painful to use, and give up on improving it once the original pain eases up a little.

**Comment by jeffreykegler** [comment]
@dabrahams Thanks for the careful going through of the Leo eval writeup in https://github.com/jeffreykegler/Marpa-arxiv-paper/issues/11#issuecomment-1358325644.  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by dabrahams** [comment]
@jeffreykegler You're most welcome; thanks for making the effort to write it down.

**Comment by dabrahams** [comment]
@jeffreykegler A quick question: Is it true that `lim0`'s transition symbol always matches LHS of `top`?

**Comment by jeffreykegler** [comment]
I take it that lim0 is the mainstem of the top. (You aren't referring to v2 of the paper, and my revision of v3 has changed since the one I sent you.) Off the top of my head (it's late at night here):

No, because of indirect right recursion:

A ::= x B
B :: = y C
C ::= z A

Otherwise, there would be a fairly obvious simplification of the Leo items, since the dotted rule in lim0 is always the the dotted rule of top.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by dabrahams** [comment]
> I take it that lim0 is the mainstem of the top.

It’s what you defined as lim0 [here](https://github.com/jeffreykegler/Marpa-arxiv-paper/blob/main/LeoEval.html).  Yes, I think that’s the mainstem of the top.


> No, because of indirect right recursion:

I’m looking right at a bunch of examples with indirect right recursion where lim0 is… often the LHS of top… but not always, so yeah.

it looks like for me, discovering lim0 while having only a predot origin means a linear search through other completions in the Earley set of top.  That's not terrible.  I could also change the chart to store a little more derivation information, but I don't think I need to go there yet.

**Comment by jeffreykegler** [comment]
Btw, I have just revised the document on restoring the Leo stacks: https://github.com/jeffreykegler/Marpa-arxiv-paper/blob/main/LeoEval.html.  The revisions do not change the algorithm, but they do add clarifications, and make the doc up to date with my current terminology.

**Comment by jeffreykegler** [comment]
@dabrahams Due to the revisions I made to https://github.com/jeffreykegler/Marpa-arxiv-paper/blob/main/LeoEval.html just now (see https://github.com/jeffreykegler/Marpa-arxiv-paper/issues/11#issuecomment-1366740891), and the revisions to the arxiv paper that are underway, I have suspended the countdown to closure on this issue.

**Comment by jeffreykegler** [comment]
@dabrahams Due to the revisions I made to https://github.com/jeffreykegler/Marpa-arxiv-paper/blob/main/LeoEval.html just now (see https://github.com/jeffreykegler/Marpa-arxiv-paper/issues/11#issuecomment-1366740891), and the revisions to the arxiv paper that are underway, I have suspended the countdown to closure on this issue.

**Comment by jeffreykegler** [comment]
Version 3 has been uploaded to arxiv.org. Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/Marpa-arxiv-paper/issues/11#issuecomment-1405496907.
