### ISSUE TITLE
I eliminated the use of LR(0) states in Marpa

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/Marpa-arxiv-paper#3]
The biggest change between the paper and the current libmarpa implementation is that I found in practice that the Aycock-Horspool use of LR(0) states produced no real gains, while considerably complicating the algorithm.  Therefore I eliminated use of AHFA states, and Marpa's current items are exactly Earley items.

**Comment by jeffreykegler** [comment]
@dabrahams -- you may find https://github.com/jeffreykegler/Marpa-arxiv-paper/issues/3#issue-1206500028 helpful in your reading -- you can ignore all the many complications AHFA states introduced.

**Comment by dabrahams** [comment]
Nifty—simpler is better.

**Comment by jeffreykegler** [comment]
This issue is covered by issue #10 and is therefore unnecessary.   Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
This issue is covered by #8 and therefore unnecessary.  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/Marpa-arxiv-paper/issues/3#issuecomment-1236209242.
