### ISSUE TITLE
Penult-unique missing definition of xDR?

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/Marpa-arxiv-paper#7]
> 6.3. Leo memoization. We define uniqueness of a penult in an Earley set as
>
> Penult-Unique(penultSYM,iES) ≡def
>     ∀yDR(Contains(currentES,yDR)∧penultSYM =Penult(yDR)) ⇒ xDR = yDR.

The implication doesn't seem to mean anything because nothing ever nails down xDR.  Am I missing something?

**Comment by dabrahams** [comment]
(The meanings of Leo-Unique and Leo-Eligible both seem to depend on having this fixed)

**Comment by jeffreykegler** [comment]
This turned out to be one in series of embarrassing small mistakes in that page.  Long ago I must have proof-read it, but it clearly was not one of my best days.  Fixed in https://github.com/jeffreykegler/Marpa-arxiv-paper/commit/22b5a3a714dbbaf48a95c64a6e4c32bd7777e5c7.  Absent feedback to the contrary, I will close this issue in a couple of days.

**Comment by jeffreykegler** [comment]
I introduced \mid as a separator into two of the equations, thinking that would make the grouping clearer to the reader.  Following https://github.com/jeffreykegler/Marpa-arxiv-paper/commit/22b5a3a714dbbaf48a95c64a6e4c32bd7777e5c7#r74147686, I realize that the \mid's are counter-productive and will remove them.

**Comment by jeffreykegler** [comment]
Notation simplified per suggestion from @dabrahams, as described in https://github.com/jeffreykegler/Marpa-arxiv-paper/issues/7#issuecomment-1133647303.  Fix is in https://github.com/jeffreykegler/Marpa-arxiv-paper/commit/49336bb01a69c7c7b077b831b57b813b72c4faf5.

Absent feedback to the contrary, I will close this issue in a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/Marpa-arxiv-paper/issues/7#issuecomment-1133648562.
