### ISSUE TITLE
Inconsistency

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/Marpa-arxiv-paper#9]
```
Leo-Unique(xDR, currentLOC) ≝
   Contains(currentES,xDR)
        ∧ Penult(xDR) ≠ Λ
        ∧ Penult-Unique(Penult(xDR), currentES)

  Leo-Eligible(xDR,currentLOC) ≝
    ∃xRULE,i | (
      xDR = [xRULE,i]
      ∧ Right-Recursive(xRULE)
      ∧ Leo-Unique(currentES,xDR))
```

The invocation of Leo-Unique in Leo-Eligible doesn't seem to match the signature of Leo-Unique.  Perhaps it should be

Leo-Unique(xDR, currentLOC)

?

(Also I am assuming we can derive currentES from currentLOC inside of Leo-Unique).

**Comment by jeffreykegler** [comment]
Mistake: commit https://github.com/jeffreykegler/Marpa-arxiv-paper/commit/54a2801ccf523ff3d90358c4753927512df08927 is actually *not* relevant.

**Comment by jeffreykegler** [comment]
@dabrahams: From https://github.com/jeffreykegler/Marpa-arxiv-paper/issues/9#issue-1252913992: "I am assuming we can derive currentES from currentLOC".  That is the case, and commit https://github.com/jeffreykegler/Marpa-arxiv-paper/commit/f27df166b39eb7f3a3fa52d3465211c679b2aa19 clarifies the matter.

**Comment by jeffreykegler** [comment]
Fixed with commit https://github.com/jeffreykegler/Marpa-arxiv-paper/commit/2e20e331b857d1762a12ac575a1e026740dba5b7.  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/Marpa-arxiv-paper/issues/9#issuecomment-1236136288.
